language: php
php:
  - '7.1'
before_script: composer install -d app
script: php build.php
after_success:
  - cd deploy
  - npm install
  - node deploy.js $FTP_HOST $FTP_USER $FTP_PASSWORD
  - node deploy.js $FTP_HOST $FTP_USER_SANDBOX $FTP_PASSWORD_SANDBOX
