version: '2'
services:
  apache:
    build: docker/web
    ports:
     - "1080:80"
    volumes:
     - ./app:/var/www/html
  db:
    build: docker/db
    ports:
     - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: sponsoren_crm
       MYSQL_USER: sponsoren_crm_user
       MYSQL_PASSWORD: sponsoren_crm_password
